### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#44]
## Description

- **As a** student,
- **I want** the ability to switch between light and dark themes,
- **So that** I can maintain a cohesive experience with other websites and applications on my device.

See https://css-tricks.com/easy-dark-mode-and-multiple-color-themes-in-react/

**Scope cut:** No manual theme setting by the user - just use their browser preference

## Requirements

- Scenario 1: No theme preference
  - Given I have no light/dark theme preference set in my browser,
  - When I visit the site,
  - Then the site displays in light theme.
- Scenario 2: Light theme preference
  - Given I have my browser set to prefer a light theme,
  - When I visit the site,
  - Then the site displays in light theme.
- Scenario 3: Dark theme preference
  - Given I have my browser set to prefer a dark theme,
  - When I visit the site,
  - Then the site displays in dark theme.
- ~~Scenario 4: Change light to dark~~
  - Given the site is displayed in light theme,
  - When I click/tap the theme control switch,
  - Then the site displays in dark theme.
- ~~Scenario 5: Return to the site~~
  - Given the site was in dark theme the last time I was there,
  - When I visit the site again,
  - Then the site displays in dark theme.

## Tasks

- [x] Add CSS media queries that change colors for dark theme

**Comment by Sahad-09** [comment]
Hey i would like to work on this. I give user multiple color theme option if you would allow me to :)
